apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects.yaml
  - platform/namespaces.yaml
  - platform/cert-manager.yaml
  - platform/traefik.yaml
  - platform/argocd.yaml
  - platform/system-upgrade-controller.yaml
  - apps-appset.yaml
