apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fumirai-lunch-prod
resources:
  - ../../base
  - frontend-env.yaml
generators:
  - secret-generator.yaml
images:
  # Promotion = change tag+digest here via reviewed PR.
  - name: fumirai-lunch-backend
    newName: docker.io/lecongtuan/fumirai-lunch-backend
    newTag: latest
    digest: sha256:8a78ed78ce8f3c7385383b020795a801d56b9e50b81a733519693ea42992f55d
  - name: fumirai-lunch-frontend
    newName: docker.io/lecongtuan/fumirai-lunch-frontend
    newTag: latest
    digest: sha256:27deb32bd3855989d06f3f4e6dd7a1dacfb2eefb1fc05c8e6a6fc0af18892585
patches:
  - target: {kind: Ingress, name: fumirai-lunch}
    patch: |-
      - { op: replace, path: /spec/rules/0/host, value: fumifood.dpdns.org }
      - { op: replace, path: /spec/tls/0/hosts/0, value: fumifood.dpdns.org }
  - target: {kind: Deployment}
    patch: |-
      - { op: replace, path: /spec/template/spec/priorityClassName, value: workload-prod }
