apiVersion: v1
kind: Secret
metadata:
    name: fumirai-lunch-env
    namespace: fumirai-lunch-prod
type: Opaque
stringData:
    ADMIN_EMAILS: ENC[AES256_GCM,data:mfNAtCuAvllQfY9yhls2uzbuo5l+GuVVqStCkcpp,iv:LGu4YEun0E+YQiWHfWC/0D4wa/8ruvMtc5RlmvXek6g=,tag:ORdQ6NqyGBjZlpkOrrY9uA==,type:str]
    API_PUBLIC_URL: ENC[AES256_GCM,data:pYkm+bbgD7mjJLlqEaR0UovT7h+BFGQo5OKcDZYH,iv:xWkqhoGMWFmsZntrSBAA/eDCEsWZLEWmtpSYRnJRfVE=,tag:6+pPbCccf2+7sHMn02nuBQ==,type:str]
    APP_WEB_URL: ENC[AES256_GCM,data:cv6CjS9kRxlXtooAgq7+2dPxyv3IYzBTrG4=,iv:GRbpiOzRe2qf2M1FHzKFPZGeQ5XrCSsYNuKKmoGitWg=,tag:wQc3TcjZm26GXjosIrgseQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dvE8JBnZQW1yJcIZcZbpM8WAXe8X45PwKajuNnPBJrFZRHW5A7hMLeQKg0cCWGyibwZQIVSfkrM9K+6bC6Y1FT9h0NuR8/hPhC0gglI/pGO/r7IBV0T3vAbk96BSGnMPd7saiYsUqn/LrJI0Kt6NEPyNlIwuzwPud2tm9SCN69UBwdWnQq6pilEWbekzkpIxqXIkVKiZ+utRs6FwpsfgqDaRKsA0cBn4kE+mOw==,iv:yXZU/Qq8WftwcxhTv7RU4xXU+7VISJTWdXfTdxmQ+aY=,tag:gbpPdeaUc5ThRSILZslt4g==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:wrnCepBhP02vMrrlIbIe8iZqD6sq93xuzQSE8ne+cGEm20oUTavBsiHwes8yXgk9e4/dnck=,iv:PQlybrBjjQ1r8HVq/+A3A327Ik4QAbxQU34kmtHDOz4=,tag:cM+x1l+B7q5d551n00kzEA==,type:str]
    GEMINI_MODEL: ENC[AES256_GCM,data:a+PJxlXX3ojHJI4l6NjS3g1qb+vy,iv:ctQddSzh6kTzQGRVxaI808gtQaSK/I8Ystpb3XmYjxs=,tag:T0R1cbt/yDoWMKpxy+ngOA==,type:str]
    GOOGLE_CALLBACK_URL: ENC[AES256_GCM,data:EOgCrqkuzcDdSw0UwG0qgxkCbCwoavvHzX8Wm5QItfl/JHpzSvC5jAOFK8d7hAFAyHNY,iv:WtDsDEcUPUVEifLajzxbwlm1VpUxoCd/H/BPjnIbj3Q=,tag:23haq6O1Hy4opx77sbSrxw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:AkCK/DCSAjcLYsWmCFVFTlHZ+Dbk84OwKZT6+AlDqysJ0codsie6YFwjJpLHYEI47N5RT/HEUSlbEjE5Wqwwa7foInk9pFHQ,iv:QYPSU25tlOBICdZMwqEL8iJugA/YgFUfD0sWfV1VXUY=,tag:ypF99BRESqtYXaBzlhWnpQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:tYps+mtmv/nB7OVIi03QwMkyBzW/t+SStdbbJgKjsATdGn4=,iv:N3Q8Ml5g4DtxJLchbuY3v7vDDdPKxH4Vg8EajHYdZ04=,tag:OnWcvvzNiHFdrYBxXd+rgg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:tUU4u+1e1V6gV1erEEG2b00PBU7pSJrDP+xEZQvVBNF5gsgg,iv:elBxK4mooiO5N2Z+Quzg3vdWfr3h0R56SYTo7CBX258=,tag:gUk++9n4qjSQE9VgblI+BA==,type:str]
    ORDER_CUTOFF_TIME: ENC[AES256_GCM,data:qoJwd0o=,iv:orB4F+Y1gg8RXJfzfk4+4zITYOpduLzafEABbYm2FjU=,tag:dUYz1cser9hi+atBw7IKnw==,type:str]
    GOOGLE_CHAT_WEBHOOK_URL: ENC[AES256_GCM,data:3PwLTuAdh9VxubUw5crOue/rFTFWrG7DM1Jrky19Ds7/VUDko4Kbr2txzAgevaRWUXGnveNcrt/cSA3ZGbhrJXLczXrHhfhP1WZ1cTwV9dxVBzBxxaO/jRf5MF2MLdN4DQpbllXn/iDGCMliVKgdHEOzNAxvs6qagpEYevVAe4//o3g72e8wHhoMNrwrE3MKA4+76a1vXz8=,iv:XBFlWSZ0fCz7kXHcbVIHjulnTt2KpechTUoWIhT4vmQ=,tag:QdCoqtaFy5fCbtSHE+Vweg==,type:str]
    ORDER_REMINDER_CRON: ENC[AES256_GCM,data:cPG78D0Hx+yfHQNa,iv:JR0MoC9T7rN3HuyIa5A3PS56JANcgYE4Cj4TIxzg1TE=,tag:pGwx5xQeFpss9ZIAvRPSpQ==,type:str]
    SUPER_ADMIN_EMAIL: ENC[AES256_GCM,data:hWREYpa74Gb8x4etp7S0cb7PRA2hEQXzR1Mpe00L,iv:Uct38ipgfo1XoOyR6IF5QQusglbftuICLsMOL7YA7K0=,tag:swFSIcuKtyeS9AodK8oRqg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:pVM9F/sexo0X2lxyqmaLWceC+MJuHz1zeOTYzjfJB6g9HWekKV+OtNvbnmWR4EyN/Yux7qkUyZ/bkBtzWuu6sPc85I8mx9kKX8iHg/l/JibwypjNjEkgLQQKPkjVAZwRgS4nLVcdMyUdWoj+OnX4EA==,iv:h0YIITuBOeewPF+zCPkuyGIcGq5r9cwhaLzFZqKczPs=,tag:NZXVcoEIbZQUlub7qtINDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVjRnbS9lMEVNV3plMC8x
            ZG0zS2lqZUJQcmo4dDdaWmlwODFpMjdYNkNJCjA5V0M4bkxOOU82Zi9Bd2Y2WUl1
            NlMxeWNzZVQyNVdtV1IvQ21qY3hVV3MKLS0tIEtGQ05NTWp2dWtkNE8vWGx5emp3
            TmFYZURBVmNQVXZKUEZFaVdqOW9SZkEK80FxHaAQZuGL20vWzFcKiXF0a/SVwbNq
            nWiOTlY/lggSMFxHfSS+jCITMRQsBY+C3yDrMk2W/+M6Yh1W7ftE0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgxn7hsah8vkxpsvgu38skcrv50ddzdw0hd69wzm02m7pzmecycs4nddp8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:19:33Z"
    mac: ENC[AES256_GCM,data:91WfQ5az4GmzvRElQRumxasBSZteavPEbyd+EWynHb7slOt2jBKPjqhtij6W55CWXpAHKmGWi4CmbQqBp3Q5bYCgO2txjWaEzBqsZwQUNH4tRlULNdv+bYU3gizaxIMmRDXP1BhaObTgOWzTyMw1NdPgxuupo8ChsnHygEE9els=,iv:UWeqEK/YxnPdoMq4aJTdSwoLrGVSDNPc6CkcEQzCJ/Q=,tag:ty5TWZmzwwooh3FKmZ9Bvw==,type:str]
    version: 3.13.3
