apiVersion: v1
kind: Secret
metadata:
    name: fumirai-lunch-env
    namespace: fumirai-lunch-prod
type: Opaque
stringData:
    ADMIN_EMAILS: ENC[AES256_GCM,data:HRNkggIIIYe/u9nLLXchslxsdQD0frRKKSJk+yKLIi4koByUI8ZxpSSjiz5xbr83fCewlHaIqL1NvwHgfBB8zgmVn/U5QGn9vRUk0vyEw9foZePcn57OJf2D+u7/SgVD4s7pzl8fSXoc8LJkW4nkdNbw5qOD7pI2InCbwF4bPKsoDtB159gEU4x89DCOJroMQYzXVX56mHB/lt/2l9LrrZV32woMkVR2asnzgM3nxFv7VGtsDQoa,iv:CHd5srR4hmfH6NOsUJcFT+HLAv7H7GTNeLc/a1AVdKc=,tag:erscXqYuuPdPr6ppGKwcNg==,type:str]
    API_PUBLIC_URL: ENC[AES256_GCM,data:VJrq2Epj1VPYfijesIG9NgZdjA2KtwkF8m6sg4WC,iv:S48Lf8Se8grYmGIFvZlB71Aj9sBMiVBue6prx9hfZHw=,tag:0c5XEPV8D0bBW7KPEzHu/g==,type:str]
    APP_WEB_URL: ENC[AES256_GCM,data:jFXb3v+siEVHDUpbyWFOWruDbflNo5XJVAQ=,iv:calk4/FEE97VnYF+eBOlTTzget1MwPnmHFvO89QeecA=,tag:aReA7Iwf9NaTD3krT7fdbw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ekk5YV82Pf2eIWHjheuE3cDEdF4YJVnEsgXpLImWUipuHsC/QKISk3eegemLQ73i6PmopWaUap6XDqDgR52GI5CbljWVQETaCRSbmKSulZt73PVztl/goOa8nqHpjbfoNyUAlz31oBX2V5s/LKqYqmtDjUsQtEeXddhMu1kr8VXUgtXfJMvIluyMpUHuYztgjKoKVO8kvtmBwlJwhBCmYJAAKCmm2JZVQwN7lQ==,iv:1ajJdvBV0mCGqLab67CYtgH7B+TrDkDroIPkJgmKLmI=,tag:fdh9Ix0e048n+G5NMyvwHw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:wluFjNfoi4ERPQrjEhHQhQjgumRW5H4Ku7VeQHd8nshNz4/qKPWn7ty5jWULQF6/jn9eJuo=,iv:EkBL2oYrIqs0Rrkzbp8/xgQNmPi6vWMetSFaYYhWf/Y=,tag:+hZq/3TTlVPPlOvyR/SIpA==,type:str]
    GEMINI_MODEL: ENC[AES256_GCM,data:QodCkNLwwRQGGiWOcOKb7g==,iv:2zG9nrHKOXF/VOR7fcfvoQbDFT17abNkluhBS8z1sCg=,tag:kpp7V2nDv43EyIvVgInYeg==,type:str]
    GOOGLE_CALLBACK_URL: ENC[AES256_GCM,data:Zo8rVdEpAvG9CtN/1IkU34keae3bbcPLRjIe5TS9DuYhkcD5XliiAD066TCIeI5bZNKH,iv:ybIkolrQi6OVwQyTIVNlamSDy31q9jfzCllNTyj0u7k=,tag:Y6dMIfknIRu2WNk4sJxDNg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:dAsZUuQUwHqXvVLEitznzIpzxjk4wnCM7c35MLn6oGitJ+XjkALTkCiQ+V9ELK8YwA9Ti6sP/UkjfRi9Cmun9P5HCCPLpiY0,iv:W2aCfxHppjVcZ0X+wURtw9E1dOwB5MYb3zhrcw/KszM=,tag:liXzcPg+PoShvejGzDMAvQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:qyckBEmEJ0RvpRT1BMfcS7EKvtw5UkSaRmRtD0PvtB6QUvM=,iv:1iME43wz3nwxraO/0yrNBUsntaUmFk7eJ820zRJ+8fw=,tag:euC60UNisyhbxis7ny2ZxQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:JrjS+MqjJmNqePGf6iD8JhiGoQZWdah047U2dPzdnNnrfnVvlAGUIgqf,iv:mVUZAZFRLAUzfBd4dbPhU6x94ycrXB6qpd01zU3SLBY=,tag:HbJEVUAa63+4ykn6eFuqcw==,type:str]
    ORDER_CUTOFF_TIME: ENC[AES256_GCM,data:WNoZW9Y=,iv:jMo7qUGxYwLu3TY9jfWcF92FWMJU90cgatyQpNq/F9E=,tag:sZbpZjXZYtqFqTRCw53MLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdDgxVEEzek9OYWJxSTNL
            enhWTVNnNHFMTms4OFJLL2RLMlVuaTFDam04Ckl5b1NjcmdRdzFRMy9aQ0tWRXVx
            VU9KSjlKUFhoZWtuZEtYNEo2SEZsU00KLS0tIDYzRFdQWDFXWlFBK1BwQ2VJR1dF
            YVA1STFWN2NVZlI5Mjd0YnYvcEF6ekUKLz3+m7VRxYE6vpyKyXrJ8HdoUkn0Jjex
            mVjXZOl+ckQgASPlrvocbk5SzX8A8EfccHguu9B1T01Gl361ULmAsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgxn7hsah8vkxpsvgu38skcrv50ddzdw0hd69wzm02m7pzmecycs4nddp8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T05:03:18Z"
    mac: ENC[AES256_GCM,data:LzV7VHaIq8D10+0KgAxXrIAMjB6QDCHtZxP1U3WXkV/lVfNR9zKaqWZOm3NoVxTZfZDeG6ZJPulcLD8tl8izQU5T9zQcbc+kwzMdCifWfHLbkq8xo5HsNZ52JXmPdw2oAOl1hfNQ59+sav4td0gTjsH0ekUoM+wcWEaf7ElY26A=,iv:Y0T9Xrqrfuw7STRbFNZr3R63rXwqLowFDEIjAYaxNRw=,tag:7K/m6KfALuIUVze2H1rltg==,type:str]
    version: 3.13.3
