apiVersion: v1
kind: Secret
metadata:
    name: fumirai-lunch-env
    namespace: fumirai-lunch-prod
type: Opaque
stringData:
    ADMIN_EMAILS: ENC[AES256_GCM,data:+Iavgero3poEZ6dEBwFawj/KOWhUosK8hBOk46EH,iv:D/2GZ8HaRXiuC12JJn2EldMQ5frkxN/zKwGC3vrKNV4=,tag:9dmgiKVIkgYgi1lSyJl8zA==,type:str]
    API_PUBLIC_URL: ENC[AES256_GCM,data:QGT9odaP5xHt6pBSwTEBPctrXjRkgUIdyxfb1Uom,iv:xqWurPAMEd21ycJXJtr271BuRSxS6n8ZR2wdXK0wpAs=,tag:Ukllvag6NIK026+MBPGKNA==,type:str]
    APP_WEB_URL: ENC[AES256_GCM,data:8j1AIchH6gfY3PFWSV8phRywcjjZH8/jifQ=,iv:oEB4o2VfAnC6RLBx8zAvAnka43FK6nxeW1WWtu7jDjA=,tag:Uw5RBdQkFTqqpOy8/eQRkA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VXOkbULJs/1RQDZdVpjuCCMV/HcZtdEi3bD9OmTIZhH9YqCzGsNl6vQlclo6Ep3pZH66WzZkCv7YThQZmRtFxbQbVG8ZiObsijT70pXY6ebwYl60nqyINr6wYEBAosImYHOiCs3Loh2tXTOrAQd4U1/LUz4qtNSGk7njZz/gIra02chXYB/oKuMF6eFy5JPUkGstpSA/SVA/ueEIeaISCeGqBmC/2cBNd6Yn+v4HPSED+mteRvFet25qw6s=,iv:CSqo5X/wi+F8rc/JvSbDi0TuIF1PNjUVwV0ADA4+M1M=,tag:CXuoQYIafLUZH8MFK1tZBg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:fIOmzVFkFz3POXtFBhYfNhpH+Fs2cguSi5Fuf9Q3iPG3Uf+sNPgITSzP+mBitNyPWT6aeek=,iv:5K/fadXQVR38OL8MDsFjbEaqxuGnbxrqNrSohjntAZo=,tag:h8P4ruV5H3xySARIHlA/Mw==,type:str]
    GEMINI_MODEL: ENC[AES256_GCM,data:0djyHqvcBuwk0PbBbNZ0/XCGnOkN,iv:wOdZw2hG+YbdPJGdGgJCldrShQCRPOEO/n1Ppgrp0eI=,tag:JSCEcIOoSMQfeCTjugh0vg==,type:str]
    GOOGLE_CALLBACK_URL: ENC[AES256_GCM,data:KJKMui0YdtLh8SeC1tecan36qM03+/MnErWN7ITzj3fG9iZ2WGPidRSEcBTYt7MS+7oB,iv:9/KnMHWVk6+3I9/AOwaF9k/oMC5t06zgKpY92F7TQIk=,tag:qeuDUtWRkUc9GiO7iytqQw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:F7owSd1nUS0vURaQ0TvZs9P737+STfhzKEtOxzqZwxejWg6fv9bX7ypGg1HpzdbKassMLmGY7SafP48PxK2SjyfAlfsfn5Q4,iv:ItkD1UiKZxmk3xSezrceCKSSQihTko5m3nwuBfPpf6o=,tag:iIYNNFoArMQwTnugaimhQg==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:oWnGCnKqjr4W9CD4tw/zk/oekmVeqKB5okHtChbl357dMck=,iv:OIOUjyDQiAjEsPqZ2ngUGEC/tL6M9jLPtg9fa4Z8IbQ=,tag:QoOPbzS6kno7eNvqcZsCBw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:pJ/Fm2WC7H33uSMiKgAompsSA86iNeqgaBszvMzIXr/aZRfo,iv:5Jq60kwUfKelt+KUAjWt925v+pPTIUlfizMLMMbKkhY=,tag:5uI4JzrAA+fRvdC11mVuww==,type:str]
    ORDER_CUTOFF_TIME: ENC[AES256_GCM,data:yPPptqk=,iv:agt2JxgykeyKieZk1M2NiO+5Jcax2t0syc4c5UdxRCA=,tag:0K57oh2w/PdMPcpp42p7gw==,type:str]
    GOOGLE_CHAT_WEBHOOK_URL: ENC[AES256_GCM,data:Df3GSQ+9jOAUQjTPYIlyTOwFQXwf2aQEkuG9U5/ero9oYIFEB9dR04UPmPEY/1+OB+T6aWgl3QJV8qSnBC8ptSmBQn8nXd/Bouogydz3jsKmT0EJNV9NWRmd23m6i+xf9j+pn0loSMkQojBDYiM7BqL673ZdFKbEbWuGx/5s8mxxAue1a4Q758oFlguqi9GRNSjlMZwsMj8=,iv:9MfFqO9Fxq84asO10CdC/I/0ecXwf7Qpg9B+nf3NASc=,tag:T/LBito0lKGD9KxCosF+Cg==,type:str]
    ORDER_REMINDER_CRON: ENC[AES256_GCM,data:qydHEoEWF/htwgFv,iv:vNmIIux/EiwwMGDAeD1tnKaMtndPCYe9Q2AtOlYHXKg=,tag:HPi8e/3kgGunamF/p30zGg==,type:str]
    SUPER_ADMIN_EMAIL: ENC[AES256_GCM,data:L5N4Mis5Aa7FOGl/+Py6Uz73NHTOJ0NKREa8b40C,iv:RcYkVnZ/HtdrFUK9f/w8Z1cvOUkOUC9jTCRYcZILpr8=,tag:56VCiXDTnQjSK4B1Jwk2Gg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:HNTEnd4io4hL5MjRuh3ctBxM5gvz0/L8blgSZEI/k4XJhdbzrZVIpuVmEFEj+OXJzzW/Lx2NQFVp8R3HuckwLJMEiQZnMUo3l7Yrh1u5NnU673g+tPOiNjGXKa2W6DUdg/xTvrqwg+89QuT3CAaSMyEDJQ==,iv:SE5E6lzc2jTm9GNdlbJ8WUm6F0xktGiUGZhhA//+3hA=,tag:kKnun+YEheSdbP2u6qo3iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZHJiK3dLZXdvSkVxalc2
            ZHBJaWU4Um9vQ3l5WGovYjU2RUdYa0c0bVFFCm0xcytJd3BBZCsxK3k3dVF4aVI1
            R0F5cDdVTmZ1M3ZUM2lZbGZON2tXbTgKLS0tIFZwaDlsRnJkeGdSZmRxMHFkVDE2
            M0dKZEJzUG1aR3gybzdCNjBKQlVlZVUKCsI1mbY0tHr27aJMYo+sq8Lp5BTZGisg
            Uo1K2JeuyV4fPifAbamV7ggrkYs5Lg/CdAra7swljAQ1O/4nRYgJDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xgxn7hsah8vkxpsvgu38skcrv50ddzdw0hd69wzm02m7pzmecycs4nddp8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T14:42:40Z"
    mac: ENC[AES256_GCM,data:Tu1orW79fjoDaGdkm3lhUh23jC8cI/80VtDdMC61Kj6gnsQmKUfv0mDJ0fAxvJI6wJOuXC6JrQnO+rRdbKT0ChA7fwTB/TEmvM/VQaIfBTbuNsmObsQXWNYo9CoiE0S5scaBhjEdoHVxsfFm46bYYcGuynMs8PteYgHM8VzxPio=,iv:3LQy1IJTR95Cvrscv+s2bQ6yl1I3Ib5jCrPROWav8OY=,tag:59FZCSlFqkHGq7BnNQBNqw==,type:str]
    version: 3.13.3
