apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: platform
  source:
    repoURL: git@github.com:lecongtuan-fumirai/gitops-fumifood.git
    targetRevision: main
    path: platform/system-upgrade-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true, SkipDryRunOnMissingResource=true]
