apiVersion: v1
kind: Secret
metadata:
    name: fumirai-lunch-env
    namespace: fumirai-lunch-staging
type: Opaque
stringData:
    ADMIN_EMAILS: ENC[AES256_GCM,data:OpTwm+hTDYKx,iv:a2yT7gIylCaSmXX0pyDQYTUuH1qdKUujbIWTgHzNNlQ=,tag:9GJnuu01SRKJUguP2D1pEA==,type:str]
    API_PUBLIC_URL: ENC[AES256_GCM,data:nXSkWaMUfytuv9YDJWaUapo+U4xuVVg9rK8DyNYR0PO2/A==,iv:WbIVw8Oaz6PbYWUk6gCUdpxMRftXlqlrFbMpfnb9O5E=,tag:Ch+ozXOrkehktZHwXgBz8w==,type:str]
    APP_WEB_URL: ENC[AES256_GCM,data:fLsBIO+p2rAMS7iLzW1QqMyfPz2gWctYheZrSj7qfzVrEw==,iv:wlAflXA6EXWS/1zbbREcx4liCq77ujyIGI+ZYcp/pco=,tag:mq95N3Sg2uOkHVT1qdL0hQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:NuYOh8idIKB/UN2Lz9d+TrqedxTnmPpNuffM/PpmMn5t,iv:SmuagTjMr61cvIubv57Vx5c8Bl80vT6ip4u1fuZ7DHY=,tag:IAnQMC9w/ocvLK6BS+mbGg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:mHrDNfvglwt8,iv:JnTZLuZfrwdF2jXHkmwShPipFVKjl9anu+vnboS9QlA=,tag:fUZqDOWR+4KOpHjijMmvDQ==,type:str]
    GOOGLE_CALLBACK_URL: ENC[AES256_GCM,data:i9pTiV6PHG8Qe4ZCeNz+8pxkIcdtqZJcP1hXRaZKDZUuUdgPONTACGUag0H4iZycuD307mRG7+O34Uo=,iv:b2Q/D1ukyVIJV+PsmhuYltBNnHkcEoV0my9OWlP9UOw=,tag:kJsVO/hnuvltBDvJfjQblA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:yVvV/EoOyku0,iv:7+giDCRjMlmewaVLbm4+RJsuIldf2c6T4sz/XVftxH8=,tag:6SuINs1UmJPITllFKYrdxw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:ha/uKjwre8/0,iv:52Afnrb4h9AnjgNki2sMhJxHH37NSfspUMDQ+P18gaE=,tag:HRo2gdF8ssL/Ka9LQOohzQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:GXDZ1YgmWuxwKq3Ka06oBAF6Nl+gyWNyFTyj0rtatIPf5gQPP4o4F0tKYdc=,iv:7TTE1n9V/EFdjOkFjyFpZerojhqY4hynnBGyZzgDhIc=,tag:8NImLDHUpMAYqbGEfPRv2Q==,type:str]
    ORDER_CUTOFF_TIME: ENC[AES256_GCM,data:KRAr2t4=,iv:lh4z7V7QdKTb2hJf7hH9bNfIIdZxdLfBnkeOuo2kDYY=,tag:e1dJpJ1/losImuppsdXb2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xgxn7hsah8vkxpsvgu38skcrv50ddzdw0hd69wzm02m7pzmecycs4nddp8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQXIwWmNYOXVHRDFqM0o3
            bGZXa3p2eHhPVGs2dUwvaUgza2VBMncxWGhVCjl4UHJXa3NydGlLMkdtcTVEWCs5
            aDRWcmNiYlZsTUVoTDFXRE5ST1J0Z1UKLS0tICtBem9hdEZMR0dhZlRWUzFNblJ6
            bUJLbXhOdlhyaCsrbjhMbVEwYmNndjAKlzmznz4vX6frjKc02kQ0Z37LMO7Merih
            HWT9wNTt9s3EHbTsxDz34fQ26j2I8G8C5FRrRjVenSLdDURLWFNQ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T02:36:35Z"
    mac: ENC[AES256_GCM,data:ohQLeRYN7KzisF54O2gPeAX2WkfuseM4bcsFoETqUYEuW3OFoo0UeqlFnZcNptWWtfMGCAMDU0vu7ut+5nqVgadh2rza5m8l2KZAEB62FOJpRbPWPnoN/aPjwlHiA5lXnq8qEuafbgNZOzAHgRCxudELV4O+do4xeJH2xUQMy4o=,iv:rsbfB9QGsnQsjoQpeqrg2ngZAlF/umZif4UgIXGR85k=,tag:6oqSGiy6MWk9gQrjDCqvEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
