apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: floci
    includeSelectors: false
resources:
  - pvc.yaml
  - floci.yaml
  - floci-ui.yaml
  - ingress.yaml
