apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: fumirai-lunch
    includeSelectors: false
resources:
  - backend.yaml
  - frontend.yaml
  - migrate-job.yaml
  - ingress.yaml
